version: '3.9'

services:
  rebeca-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rebeca-app

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production

    restart: always